### ISSUE TITLE
ํYour program is too slow.

### ISSUE THREAD

**Issue by 9meo** [rkcosmos/deepcut#1]
You have to create init method to load model instead load every time in tokenize
[https://github.com/rkcosmos/deepcut/blob/master/deepcut/deepcut.py](url)
def tokenize(text):

**Comment by titipata** [comment]
I solve it in https://github.com/rkcosmos/deepcut/pull/2. Not sure if the PR will be merged soon or not.

**Comment by rkcosmos** [comment]
thanks, will take a look today evening.

**Comment by 9meo** [comment]
I found that your accuracy is character level and I already test word level with Inter-BEST test set.
The results are https://goo.gl/8EUu5z.

**Comment by rkcosmos** [comment]
Can I take a look at Inter-BEST test set and your code for generating these result?

**Comment by titipata** [comment]
+1 Yeah, having a test script for validating performance would be great.

**Comment by 9meo** [comment]
could I take your email address?

**Comment by rkcosmos** [comment]
r.(my surname) (at) gmail.com
