### ISSUE TITLE
Adding document-term matrix to the library

### ISSUE THREAD

**Issue by titipata** [rkcosmos/deepcut#18]
@rkcosmos, Can I add document-term matrix calculation to `deepcut` (similar to [`CountVectorizer`](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) in scikit-learn but using deepcut to tokenize Thai words for a given documents)? I think this would be helpful for people who wants to use document-term matrix for topic modeling like [Latent Dirichlet Allocation](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html) or [Latent Semantic Analysis](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html).

I proposed something as follows:

```python
from deepcut import DeepcutTokenizer
tokenizer = DeepcutTokenizer(ngram_range=(1,1), max_df=0.8, min_df=0.1)
X = tokenizer.fit_transform(documents) # document-term matrix of Thai text
```

This is still not as perfect as `scikit-learn` count vectorizer but good enough for usage :)

**Comment by rkcosmos** [comment]
looking very nice, PR merged.

**Comment by titipata** [comment]
@rkcosmos thanks krub! You might have to update for `pip` install a bit but no rush krub 👍
