### ISSUE TITLE
deepcut with user dictionary support ?

### ISSUE THREAD

**Issue by ping-godhand** [rkcosmos/deepcut#22]
Dear K.Rakpong krub,

May I have a suggestion about using deepcut with user dictionary support ? 

According to your sample "โรงเรียน", there are many words which shouldn't be cut such as "ขี้เกียจ"

![d1](https://user-images.githubusercontent.com/15793866/31120823-11ef4c7a-a860-11e7-973c-b50973edd307.png)

And I have some specific word which I don't want deepcut to cut it such as "หูอื้อ" in middle of sentence (if there is only "หูอื้อ", it works fine !)

My workaround for this issue is to enclose every word such as "ขี้เกียจ" / "หูอื้อ" with "#" and replace them in the last process.

![d2](https://user-images.githubusercontent.com/15793866/31121225-8b28ed16-a861-11e7-9dd0-fb3a064baff2.png)

I don't know is this the best way to achieve this, but it would be great if we can input dictionary for the corpus which shouldn't be cut because of I think that there will be many users which will have their own specific corpus which don't want to be cut in their own project, it would be nice to have this feature.

Best Regards,

Ping

**Comment by rkcosmos** [comment]
Hi Ping,

Adding # is a nice work around. I agree we should implement this feature properly as many people asked for it. I will take care of it soon in the next version.
