### ISSUE TITLE
Make custom dict as an argument instead of looking particular directory

### ISSUE THREAD

**Issue by titipata** [rkcosmos/deepcut#26]
Probably we can change [this](https://github.com/rkcosmos/deepcut/blob/master/deepcut/deepcut.py#L313-L320) to format like

```
deepcut.tokenize('อยากกิน', custom_dict='/path/to/dict.txt')
```

where default, we set it to `None`. It's going to be easier to add manual custom dictionary.

**Comment by titipata** [comment]
This feature is only working when installing directly from Github right now:

```bash
pip install git+git://github.com/rkcosmos/deepcut.git
```

We will update to `pip install` soon after code-review!

**Comment by rkcosmos** [comment]
Ops, I was absorbed into other works for a while, didn't notice this. Should we update the current version to pip?

**Comment by titipata** [comment]
Yes please! Can you update the current version on `pip`? We can close the issue after.
