### ISSUE TITLE
Create web application for deepcut using KerasJS/TensorflowJS

### ISSUE THREAD

**Issue by titipata** [rkcosmos/deepcut#27]
@kittinan, let's create `docs` folder to for hosting Tensorflow JS model and tiny application for testing the library. Can you also add the script to convert the model to Tensorflow JS so I can try it (thanks in advance krub!)?

**Comment by titipata** [comment]
@bluenex if you have time to coordinate with @kittinan on this! I'll be working on it soon in the morning.

**Comment by kittinan** [comment]
This tool from Tensorflow.js can convert tensorflow and keras model to tensorflow.js format

https://github.com/tensorflow/tfjs-converter

Example:
https://github.com/tensorflow/tfjs-examples

**Comment by titipata** [comment]
```js
var text = "ฮัลโหล"
n = text.length
text_pad = "          " + text + "          "
var text_array = Array(n);
for (var i = 10 ; i < text.length +  10; i++ ) {
    for (var j = -10; 10; j++) {
        var char = text_pad[i];t
    }
}
```

**Comment by kittinan** [comment]
- Tensorflow.js
![screenshot at 2018-04-01 21-33-47](https://user-images.githubusercontent.com/144775/38174439-342277e8-35f7-11e8-91bc-d2178dc2da5b.png)

- Keras.js
![screenshot at 2018-04-01 21-50-05](https://user-images.githubusercontent.com/144775/38174440-379f2358-35f7-11e8-88f7-6ba9cbc6a9c4.png)


:sob:  :sob:  :sob:

**Comment by titipata** [comment]
@kittinan can you attach code snippet on how to convert keras model? Also, I simplify the feature generation code [here](https://github.com/rkcosmos/deepcut/commit/e2fbb7bc34b87a06d45fc422e709199260d419e7).

**Comment by titipata** [comment]
So my attempt to run using `kerasjs` fails, it is related to this [issue](https://github.com/transcranial/keras-js/issues/110) and this [issue](https://github.com/transcranial/keras-js/issues/79).

To replicate the issue, first, we have to save the keras model (not just weights)

```python
import deepcut
model = deepcut.model.get_convo_nn2()
model.load_weights('/deepcut/deepcut/weight/cnn_without_ne_ab.h5')
model.save('/deepcut/deepcut/weight/model_cnn_deepcut.h5')
```

Simple script of `index.html` to run the web application:

```html
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://unpkg.com/keras-js"></script>

  </head>
  <body>

    </div>
    <canvas id="grayscale" width="50" height="50"></canvas>

    <script>
    const model = new KerasJS.Model({
      filepath: 'model_cnn_deepcut.bin',
      gpu: false
    })
    </script>

  </body>
</html>
```

run the code using `python -m http.server 8000`

The error is as follows:

```html
Uncaught (in promise) Error: [Conv1D layer: conv1d_25] Incompatible combination of dilation_rate with strides.
```

**Comment by titipata** [comment]
Javascript snippet to turn input `text` into `x_char` and `x_type` equivalent to `deepcut.utils.create_feature_array`

```js
var text = 'ฮัลโหล';
text_pad = '          ' + text + '          ';
var text_pad = text_pad.split('');
var n = text.length;
var n_pad = 21;
var n_pad_2 = 10;

var character_list = Array();
for (var i = n_pad_2; i < n_pad_2 + n; i++) {
    a = text_pad.slice(i + 1, i + n_pad_2 + 1);
    b = text_pad.slice(i - n_pad_2, i).reverse();
    c = text_pad.slice(i, i + 1);
    var char_list  = a.concat(b).concat(c);
    character_list[i - n_pad_2] = char_list;
}


X_char = Array();
X_type = Array();
for (var i = 0; i < character_list.length; i++) {
    characters = character_list[i];
    var x_char = Array();
    var x_type = Array();
    for (var j = 0; j < characters.length; j++) { 
        x_char[j] = CHARS_MAP[characters[j]];
        x_type[j] = CHAR_TYPES_MAP[CHAR_TYPE_FLATTEN[characters[j]]];
    }
    X_char[i] = x_char;
    X_type[i] = x_type;
}
```

I'm not sure what's the function that works equivalent to `CHARS_MAP.get` in Javascript.

**Comment by titipata** [comment]
**Output (in Javascript)** 

Suppose we have 

```js
text = 'ฮัลโหล';
prediction = [0.7, 0.2, 0.2, 0.7, 0.2, 0.2];
```
Here is the function to get the output tokenized text:

```js
var prediction = prediction.slice(1).concat(1)

tokenized_text = Array();
var count = 0;
var word = "";
for (var i = 0; i < text.length; i ++ ) {
   word = word + text[i];
   if (prediction[i] > 0.5){
       tokenized_text[count] = word;
       count = count + 1;
       word = '';
   }
}
```

**Comment by titipata** [comment]
@rkcosmos, Can you change the settings so that GitHub build Pages from `docs` folder krub? You have to go to `settings` > `GitHub Pages` > and change to `master branch docs/ folder` (very easy to do, takes 1 min!)

**Comment by rkcosmos** [comment]
@titipata , master branch docs/ folder option is not clickable. Is it because we don't have /doc yet?

**Comment by titipata** [comment]
@rkcosmos Just accepted Pull request krub! Now we have `docs` folder!

**Comment by titipata** [comment]
@kittinan and @bluenex, Can we also add `clear` and `load sample text` like in https://transcranial.github.io/keras-js/#/imdb-bidirectional-lstm to the demo?

**Comment by titipata** [comment]
@kittinan, sometimes the tokenizer throws an error because of the unexpected characters and it stops translation e.g.

```
รอง นรม. พล.อ. ธนะศักดิ์ฯ และ รมว.การท่องเที่ยวฯ พร้อมคณะมาพบ นรม.
เพื่อประชาสัมพันธ์งานเย็นทั่วหล้า มหาสงกรานต์ ภายใต้แนวคิด “Amazing Songkran 2017 มหัศจรรย์ 
```

The tokenization stops after seeing `“` character. We have to check if the given character is in the key first before mapping to dictionary.

**Comment by kittinan** [comment]
@titipata I fixed unexpected character in PR #33

**Comment by titipata** [comment]
@rkcosmos Now we have docs folder! Let me know if you change the settings. The demo should be available on https://rkcosmos.github.io/deepcut/ right after.

**Comment by rkcosmos** [comment]
@titipata  setting changed

**Comment by rkcosmos** [comment]
btw, fantastic work I didn't know we can do segmentation in realtime, very fast!
