### ISSUE TITLE
install using Dockerfile has an error

### ISSUE THREAD

**Issue by tanlull** [rkcosmos/deepcut#36]
Step 9/11 : COPY keras.json /root/.keras/
COPY failed: stat /var/lib/docker/tmp/docker-builder400846702/keras.json: no such file or directory

**Comment by chusri** [comment]
from the readme.md after cloning we have to create a keras.json at ~/.keras/keras.json.

<img width="946" alt="screenshot 2018-04-11 08 48 51" src="https://user-images.githubusercontent.com/2667287/38592297-80f46fde-3d65-11e8-9ff9-c0927f76a50a.png">

i think we have to create a keras.json in the same directory with Dockerfile before run 

`docker build -t deepcut .`

**Comment by titipata** [comment]
I suppose #50 solved this issue. Let me know if there is a problem, we can reopen this issue.
