### ISSUE TITLE
Can I apply this software to Lao Language  

### ISSUE THREAD

**Issue by huelee2020** [rkcosmos/deepcut#37]
I am a Lao student studying in China, so I ahve an idea to use it for Lao Language, and will it work ? and wht is the first step for me?

**Comment by rkcosmos** [comment]
Yes, the model can be applied to Lao. The first and probably hardest step is to find/create Lao corpus (similar to what I trained Thai model with this https://www.nectec.or.th/corpus/index.php?league=pm). Second step would be modifying CHAR_TYPE in utils.py with Lao alphabet. Third, prepare Lao corpus dataframe and train your model with train.py.

**Comment by huelee2020** [comment]
Yes I think it can apply. But I cannot download the Thai corpus in this
website. I registered in this website but it said error 405 or 406
something like this so I still cannot download the corpus and its manual
guide
Please help me. How to register and login to download your corpus and then
i will create Lao corpus txt file
but already have one corpus I will send it you check it for me that can use
this corpus or not?

Thank you so much for your give me an idea

**Comment by rkcosmos** [comment]
Not sure about the link, but you don't actually need Thai corpus. The corpus is just a normal txt file with Thai text with "|" symbol act as separator between words. You can send your corpus to my email rkcosmos (at) gmail.com.
