### ISSUE TITLE
How to using custom_dict ?

### ISSUE THREAD

**Issue by sompob-ch** [rkcosmos/deepcut#39]
i'm so sorry, i'm not good in english. i have question about custom_dict.
this example python test deepcut.
![screen shot 2561-09-03 at 10 55 53](https://user-images.githubusercontent.com/37973522/44966877-0202d600-af68-11e8-8d37-6c1d178a4713.png)

i not understand result in test_deepcut_custom_dict_B.
how is the process to logically make the deepcut by custom_dict ?

thank you.

**Comment by titipata** [comment]
I don't quite understand your question. It seems like you know how to use custom dictionary. Can you tell more about specific question that you have?

**Comment by sompob-ch** [comment]
how i can use Longest Matching in custom dictionary ?

**Comment by titipata** [comment]
@sompob-ch Basically, the `custom_dict` will wrap text together from the first one to the last one. It would like most sense to have the longest word at the end. Here is an example:

```
deepcut.tokenize('เงินฝากออนไลน์', ['เงินฝาก', 'เงินฝากออนไลน์']) >> ['เงินฝากออนไลน์']
deepcut.tokenize('เงินฝากออนไลน์', ['เงินฝากออนไลน์', 'เงินฝาก']) >> ['เงินฝาก', 'ออนไลน์']
```

**Comment by titipata** [comment]
@sompob-ch I hope the answer above solves your question. If not, please let me know.
