### ISSUE TITLE
custom_dict parameter didn't work on custom dictionary?

### ISSUE THREAD

**Issue by nawaphonOHM** [rkcosmos/deepcut#41]
I have created custom dictionary text-file named "test.txt" and placed test.txt's directory as a parameter of `custom_dict`. The result didn't work whereas the function returned a result same as `custom_dict` default value instead. How can I fix it? 
It should work as ['วิชา', 'การเขียนโปรแกรม', 'มี', 'ใคร', 'สอน', 'บ้าง']

![image](https://user-images.githubusercontent.com/22292305/45814730-b2126600-bd00-11e8-88ea-3291f50e6e87.png)

![image](https://user-images.githubusercontent.com/22292305/45814935-62806a00-bd01-11e8-8c3d-b5fd24a8fd78.png)

![image](https://user-images.githubusercontent.com/22292305/45815039-bbe89900-bd01-11e8-8958-cb4d017ef192.png)

![image](https://user-images.githubusercontent.com/22292305/45815271-5517af80-bd02-11e8-9adb-0f3605e6bc16.png)

**Comment by titipata** [comment]
This works for me:

```python
deepcut.tokenize('วิชาการเขียนโปรแกรมมีใครสอนบ้าง', custom_dict=['วิชา', 'การเขียนโปรแกรม'])
>> ['วิชา', 'การเขียนโปรแกรม', 'มี', 'ใคร', 'สอน', 'บ้าง']
```

You put `การเขียนโปรแกรมคอมพิวเตอร์` in a `custom_dict.txt` which does not exist in a given text.
