### ISSUE TITLE
The URL of the public signing key has changed

### ISSUE THREAD

**Issue by kittipongint** [rkcosmos/deepcut#47]
In the Dockerfile we are still using old public signing key of alpine. please change from 

> 'https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub' 
to 
> 'https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub'

**Comment by kittinan** [comment]
@kittipongint I created pull request #48 just wait for maintainer merge it.
