### ISSUE TITLE
Instruction to install from repository for the latest version

### ISSUE THREAD

**Issue by titipata** [rkcosmos/deepcut#5]
Maybe you can allow users to install directly from repository also. Something like following:

Install using `pip` for stable release

```python
pip install deepcut
```

Latest release

```python
pip install git+git://github.com/rkcosmos/deepcut.git
```

We can change to the stable one later. It's now in active development so I think it makes sense to have this instruction.

**Comment by rkcosmos** [comment]
Agreed, done!
