### ISSUE TITLE
Visualisation of DeepCut's architecture

### ISSUE THREAD

**Issue by p16i** [rkcosmos/deepcut#51]
Hi,

I'm currently trying to understand how DeepCut actually works in terms of computation. So, I've made this visualisation see how DeepCut's computational graph is constructed. 

![deepcut-architecture](https://user-images.githubusercontent.com/1214890/58434932-5185c500-80e8-11e9-9bd9-54ae194fc2cf.png)

Could you please confirm me whether the visualisation is correct?

**Comment by rkcosmos** [comment]
Yes, it looks alright! Do you mind if I put this picture in project's readme file?

**Comment by p16i** [comment]
@rkcosmos yep, I don't mind if you want to put the picture in the README. I'll let you know when I have the final version.

There are a couple of details that I would like to include in this image. Such details are:
- no. of weights in each layers

Feel free if you want to have any additional details in the figure.

**Comment by kittinan** [comment]
@heytitle How you generate this image visualization?

**Comment by titipata** [comment]
+1 for putting the model architecture in the README krub! Maybe just add a little section on how it works :)

**Comment by p16i** [comment]
Hi all, 

Thanks for the input. 

> @heytitle How you generate this image visualization?

I manually draw it in Sketch. 

> +1 for putting the model architecture in the README krub! 

Because the figure is quite large, having it in the README would burden the content. I would suggest host the figure somewhere and just add a link inside README.

**Comment by p16i** [comment]
![deepcut-architecture](https://user-images.githubusercontent.com/1214890/58486992-14c1d880-8191-11e9-9122-8385750e06bd.png)



I've transposed the figure and it now consumes only a small vertical portion of the README. Let me know if there is anything that you want me to adjust. Otherwise, I would say this is the final version.
cc: @rkcosmos @kittinan @titipata
