### ISSUE TITLE
DeepCut on GPU is slower than on CPU.

### ISSUE THREAD

**Issue by p16i** [rkcosmos/deepcut#53]
Hi,

While working on https://github.com/heytitle/thai-tokenisers/issues/1#issuecomment-497231701, I've found that Running DeepCut on GPU is slightly slower than running it on CPU. This is a bit counterintuitive and I'm trying to find the reason for that.

Do you have an idea why this is the case? 

Link to the benchmark code: https://colab.research.google.com/drive/1SuNYLiwEkOln_WGP_BekumGP4CxRm9rp

**Comment by rkcosmos** [comment]
Probably because most of the resource is wasted in preprocessing data.
