### ISSUE TITLE
Digital Object Identifier for DeepCut

### ISSUE THREAD

**Issue by p16i** [rkcosmos/deepcut#55]
Hi,

It would be great if DeepCut has its own DOI for academic references. You can achieve this persistent reference by using [Zenodo][ss], recommended by GitHub.

[ss]: https://help.github.com/en/articles/referencing-and-citing-content

**Comment by titipata** [comment]
Yes, that would be great @heytitle. I don't have permission to do it here. I cc'ed @rkcosmos who can do it.

**Comment by titipata** [comment]
Yes, that would be great @heytitle. I don't have permission to do it here. I cc'ed @rkcosmos who can do it.

**Comment by p16i** [comment]
hi, any thoughts on this issue?

**Comment by titipata** [comment]
@rkcosmos, just following up with @heytitle post, Can we put the latest version of `deepcut` and assign DOI from Zenodo to the repository? I don't have a permission to do it krub.

**Comment by p16i** [comment]
Here are more or less what you have to do:
1. Enable your repository on Zenodo.
2. Create a release on Github

**Comment by rkcosmos** [comment]
done, thanks for reminding me.

**Comment by p16i** [comment]
@rkcosmos  you might want to update citation details as well: 

https://zenodo.org/record/3457707#.XYhtQS2Q3OQ

**Comment by titipata** [comment]
thanks krub, @rkcosmos! @heytitle not sure how would you like to do that for the citation details?

**Comment by p16i** [comment]
Well, currently it looks like this:
```
Rakpong Kittinaradorn, Titipat Achakulvisut, Kittinan, Pattarawat Chormai, Chanwit Kaewkasi, Tulakan Ruangrong, … bact'. (2019, September 23). rkcosmos/deepcut: deepcut v1.0 (Version v1.0). Zenodo. http://doi.org/10.5281/zenodo.3457707
```

IMHO, these are  issues that should be addressed:
1. My name (Pattarawat Chormai) shouldn't be there. I didn't contribute to the main part of the development.
2. `bact` should be a full name of @bact. 
3. `rkcosmos/deepcut: deepcut v1.0 (Version v1.0)` should be changed. My suggestion would be `DeepCut: A Thai word tokenization library using Deep Neural Network`.

**Comment by titipata** [comment]
thanks @heytitle! @rkcosmos can you fix the citation to the following:

```
Rakpong Kittinaradorn, Titipat Achakulvisut, Korakot Chaovavanich, Kittinan Srithaworn, 
Pattarawat Chormai, Chanwit Kaewkasi, Tulakan Ruangrong, Krichkorn Oparad. 
(2019, September 23). DeepCut: A Thai word tokenization library using 
Deep Neural Network. Zenodo. http://doi.org/10.5281/zenodo.3457707
```

I will fix the `README` so that people can use it for referencing the library.

**Comment by p16i** [comment]
It would be good if we could fix it on Zonedo as well because people might want to copy the bibtex from there.

**Comment by rkcosmos** [comment]
Done
