### ISSUE TITLE
มันไม่ตัดครับ

### ISSUE THREAD

**Issue by comdevx** [rkcosmos/deepcut#60]
![Screen Shot 2562-10-22 at 11 18 51](https://user-images.githubusercontent.com/8242229/67259075-331ccd80-f4be-11e9-8220-05790c5fcbf8.png)

**Comment by titipata** [comment]
โมเดลใน DeepcutJS จะต่างจากใน Deepcut จริงๆอยู่เล็กน้อยครับ (ขนาดเล็กกว่าเพื่อให้โหลดไปบน browser ได้) เลยยังตัดคำได้ไม่ดีเท่า Deepcut ครับ

**Comment by titipata** [comment]
Here I attach the output from `deepcut`

```py
deepcut.tokenize("โอ้โหนี่หรอตัดคำ") 
>> ['โอ้โห', 'นี่', 'หรอ', 'ตัด', 'คำ']
```

**Comment by comdevx** [comment]
ผมว่า โอ้ กับ โห ต้องแยกกันนะครับ
