### ISSUE TITLE
Questions about access to BEST corpus for class project on deepcut

### ISSUE THREAD

**Issue by wanitchayap** [rkcosmos/deepcut#61]
Hi! I am a master's student in Computational Social Science at UChicago. I am taking a computational linguistic class here with [Allyson Ettinger](https://aetting.github.io/), and I have to conduct a final project. I am very interested in Thai text tokenization, and I am planning to use `deepcut` as my starting point for my final project. I am at a very amateur level in the field of computational linguistics, so I am very likely not going to make any significant contribution to your already-well-built `deepcut`. However, I still want to have hands-on experience with neural networks on the topic that I personally care about (Thai tokenization). Therefore, is it possible for me to use `deepcut` skeleton and explore some possible tweaks with it, as well as to get access to the BEST corpus you use so that I can train and evaluate my version in comparison with your original `deepcut` on BEST corpus? Of course, I am going to cite `deepcut` in my project properly!

ขอบคุณค่ะ
มิ้น

**Comment by titipata** [comment]
Hi @wanitchayap, I think the BEST corpus can be downloaded [here](https://www.nectec.or.th/corpus/index.php?league=pm). You should also check out [attacut](https://github.com/PyThaiNLP/attacut) which is a trimmed version of `deepcut`. It also provides test comparisons such as speed, model size, etc. etc.

**Comment by wanitchayap** [comment]
@titipata Thank you so much!

**Comment by titipata** [comment]
@wanitchayap I will close this issue. If you have extra questions or want to follow up with this question, please feel free to reopen it.
