### ISSUE TITLE
Upgrade Dockerfile to Tensorflow 2.0

### ISSUE THREAD

**Issue by kittinan** [rkcosmos/deepcut#64]
Need help to upgrade Dockerfile to Tensorflow 2.0

**Comment by titipata** [comment]
tagging @chanwit and @heytitle to help on this issue

**Comment by chanwit** [comment]
I'll take a look

**Comment by titipata** [comment]
@chanwit can we also do `pip install git+git://github.com/rkcosmos/deepcut.git` so that it's always up-to-date?

**Comment by chanwit** [comment]
yep, that's a good idea

**Comment by titipata** [comment]
perfect, thanks @chanwit!
