### ISSUE TITLE
New installation of latest release fails (via pip)

### ISSUE THREAD

**Issue by pcolagrosso** [rkcosmos/deepcut#66]
sudo python3.6 -m pip install deepcut
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting deepcut
  Using cached https://files.pythonhosted.org/packages/ef/f3/ecda1d7dc51da0689b2df3d002541d0d04ac4db02c5d148eca48c8e3d219/deepcut-0.7.0.0-py3-none-any.whl
Requirement already satisfied: h5py in /usr/local/lib64/python3.6/site-packages (from deepcut)
Collecting tensorflow>=2.0.0 (from deepcut)
  **Could not find a version that satisfies the requirement tensorflow>=2.0.0** (from deepcut) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow>=2.0.0 (from deepcut)

**Comment by rkcosmos** [comment]
Can you try normal pip install without using cached?

**Comment by pcolagrosso** [comment]
Thanks for your message.  You would like me to run pip with the "--no-cache-dir" option , correct?

**Comment by rkcosmos** [comment]
yes, try that.

**Comment by pcolagrosso** [comment]
I tried that and I am still getting an error message.

[piero@piero repo]$ sudo python3.6 -m pip --no-cache-dir install deepcut
[sudo] password for piero: 
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting deepcut
  Downloading https://files.pythonhosted.org/packages/ef/f3/ecda1d7dc51da0689b2df3d002541d0d04ac4db02c5d148eca48c8e3d219/deepcut-0.7.0.0-py3-none-any.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 40.6MB/s 
Requirement already satisfied: numpy in /usr/local/lib64/python3.6/site-packages (from deepcut)
Collecting scikit-learn (from deepcut)
  Downloading https://files.pythonhosted.org/packages/d1/48/e9fa9e252abcd1447eff6f9257636af31758a6e46fd5ce5d3c879f6907cb/scikit_learn-0.22.1-cp36-cp36m-manylinux1_x86_64.whl (7.0MB)
    100% |████████████████████████████████| 7.1MB 44.4MB/s 
Collecting scipy (from deepcut)
  Downloading https://files.pythonhosted.org/packages/dc/29/162476fd44203116e7980cfbd9352eef9db37c49445d1fec35509022f6aa/scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (26.1MB)
    100% |████████████████████████████████| 26.1MB 26.0MB/s 
Requirement already satisfied: h5py in /usr/local/lib64/python3.6/site-packages (from deepcut)
Collecting tensorflow>=2.0.0 (from deepcut)
  **Could not find a version that satisfies the requirement tensorflow>=2.0.0 (from deepcut) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)**
No matching distribution found for tensorflow>=2.0.0 (from deepcut)

**Comment by pcolagrosso** [comment]
Thanks for your help.

**Comment by rkcosmos** [comment]
not sure what is going on. Try pip install tensorflow==2.0 first and then pip install deepcut.
