### ISSUE TITLE
AttributeError: partially initialized module 'deepcut' has no attribute 'tokenize'

### ISSUE THREAD

**Issue by biigpongsatorn** [rkcosmos/deepcut#74]
Hi,

First of all, Thanks for a really useful library.

I'm trying to use Deepcut library and I'm facing this error:
```
AttributeError: partially initialized module 'deepcut' has no attribute 'tokenize' (most likely due to a circular import)
```

I've installed `deepcut` with pip, like `pip install deepcut`, and then written a very simple python code
```python
import deepcut
print(deepcut.tokenize('ตัดคำได้ดีมาก'))
```

And I got that error message.

My environment:
Python: 3.10.12, 3.7.17 (tried both)
pip: 23.2.1
OS: MacOS
Chip: M2

**Comment by biigpongsatorn** [comment]
[SOLVED] This was my fault, I named the file with the same as an imported module  (`tokenize.py`). So, I solved it by changing the file name to something else.

**Comment by titipata** [comment]
Nice, glad you found the solution, and thanks for the comments!
