### ISSUE TITLE
Using Keras fit_generator to train the model

### ISSUE THREAD

**Issue by titipata** [rkcosmos/deepcut#9]
It might be useful to use `generator`, see example [here](https://github.com/fchollet/keras/issues/1627) to train the model. 

We should also add `callback_list` while training e.g. `ModelCheckpoint`, `EarlyStopping`, `ReduceLROnPlateau` to `fit_generator` function in order to save the best model (divide training set into training and development set).

I can work on it and send the PR over the weekend :)

**Comment by rkcosmos** [comment]
That would be good. We will need to train bigger input when doing semi-supervised learning, using fit_generator is a good idea.

**Comment by rkcosmos** [comment]
I'm updating a small change and creating reproducible_training notebook, pls fork after my update to avoid confusion.

**Comment by rkcosmos** [comment]
ok, done

**Comment by titipata** [comment]
@rkcosmos I don't see the update. Did you push the notebook up?

**Comment by rkcosmos** [comment]
notebook is still running on my local computer, but other small changes are done. So you can implement fit_generator and call_back on top of current code. I think fit_generator can be structured similar to this (https://github.com/rkcosmos/Breast-Cancer/blob/master/src/inception1_simplified.ipynb). We would need a function like 'organise training set section' to separate train and test folder. Then fit_generator can do its job naturally.

**Comment by titipata** [comment]
Yeah, will do that! So I'll wait to see the code and will separate the training and testing to separate folder for you. I'll also implement generator class.

**Comment by titipata** [comment]
I think I'll close the issue for now and we can take into account the `fit_generator` later once the training data is much larger (e.g. we want to incorporate Wikipedia). The version that we have currently using `fit` is pretty easy to read.
